name: Lint NPM Package
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Node.js Dependencies
        run: npm ci
      - name: Lint NPM Package
        run: npm run lint
      - name: Typecheck NPM Package
        run: npm run typecheck
      - name: Build NPM Package
        run: npm run build
